//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunnerBLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RunnerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RunnerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunnerBLL.Resources.RunnerResource", typeof(RunnerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is already running..
        /// </summary>
        public static string ApplicationAlreadyRunning {
            get {
                return ResourceManager.GetString("ApplicationAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name : {0}, Assembly Version : {1}..
        /// </summary>
        public static string ApplicationInfo {
            get {
                return ResourceManager.GetString("ApplicationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture is set to: {0}..
        /// </summary>
        public static string CultureSet {
            get {
                return ResourceManager.GetString("CultureSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Culture: {0}..
        /// </summary>
        public static string GivenCulture {
            get {
                return ResourceManager.GetString("GivenCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Process: {0}..
        /// </summary>
        public static string GivenProcess {
            get {
                return ResourceManager.GetString("GivenProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Process(s): {0}..
        /// </summary>
        public static string GivenProcesses {
            get {
                return ResourceManager.GetString("GivenProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Process..
        /// </summary>
        public static string InvalidProcess {
            get {
                return ResourceManager.GetString("InvalidProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue while running {0}..
        /// </summary>
        public static string IssueWhileRunning {
            get {
                return ResourceManager.GetString("IssueWhileRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not running {0}, due to invalid state..
        /// </summary>
        public static string NotRunningDueToInvalidState {
            get {
                return ResourceManager.GetString("NotRunningDueToInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} process is already running..
        /// </summary>
        public static string ProcessAlreadyRunning {
            get {
                return ResourceManager.GetString("ProcessAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} process ran successfully..
        /// </summary>
        public static string ProcessCompleted {
            get {
                return ResourceManager.GetString("ProcessCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} process(s) ran successfully..
        /// </summary>
        public static string ProcessesCompleted {
            get {
                return ResourceManager.GetString("ProcessesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process {0} is invalid..
        /// </summary>
        public static string ProcessIsInvalid {
            get {
                return ResourceManager.GetString("ProcessIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register process {0}..
        /// </summary>
        public static string UnableToRegisterProcess {
            get {
                return ResourceManager.GetString("UnableToRegisterProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register process(s)..
        /// </summary>
        public static string UnableToRegisterProcesses {
            get {
                return ResourceManager.GetString("UnableToRegisterProcesses", resourceCulture);
            }
        }
    }
}
